[package]
name = "http_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.6.5"
ic-cdk-macros = "0.6.5"
serde = "1.0.126"
candid = "0.8.0"
serde_json = "1.0.81"
serde_bytes = "0.11.7"
